-- 1. Create Companies Table
CREATE TABLE companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  logo_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Jobs Table
CREATE TABLE jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  location TEXT,
  company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE,
  requirements TEXT,
  isOpen BOOLEAN DEFAULT TRUE,
  recruiter_id TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Applications Table
CREATE TABLE applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT REFERENCES jobs(id) ON DELETE CASCADE,
  candidate_id TEXT NOT NULL,
  name TEXT,
  status TEXT DEFAULT 'applied',
  resume TEXT,
  experience INT,
  education TEXT,
  skills TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Saved Jobs Table
CREATE TABLE saved_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  job_id BIGINT REFERENCES jobs(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, job_id)
);
