-- 1. Create Companies Table
CREATE TABLE companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  logo_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Jobs Table
CREATE TABLE jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  location TEXT,
  company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE,
  requirements TEXT,
  is_open BOOLEAN DEFAULT TRUE,
  recruiter_id TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Applications Table
CREATE TABLE applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT REFERENCES jobs(id) ON DELETE CASCADE,
  candidate_id TEXT NOT NULL,
  name TEXT,
  status TEXT DEFAULT 'applied',
  resume TEXT,
  experience INT,
  education TEXT,
  skills TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Saved Jobs Table
CREATE TABLE saved_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  job_id BIGINT REFERENCES jobs(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, job_id)
);

-- Disable Row Level Security (RLS) to allow the app to work without complex policies
-- Disable Row Level Security (RLS) for all tables to avoid permission issues
ALTER TABLE companies DISABLE ROW LEVEL SECURITY;
ALTER TABLE jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE applications DISABLE ROW LEVEL SECURITY;
ALTER TABLE saved_jobs DISABLE ROW LEVEL SECURITY;

-- Ensure public access to storage is granted (Fixes 403 / 400 errors)
-- 1. Create buckets if they don't exist (Runs only if you have permissions)
INSERT INTO storage.buckets (id, name, public)
VALUES ('company-logo', 'company-logo', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('resumes', 'resumes', true)
ON CONFLICT (id) DO NOTHING;

-- 2. Remove any existing broken policies
DROP POLICY IF EXISTS "Allow Public Uploads" ON storage.objects;
DROP POLICY IF EXISTS "Allow Public View" ON storage.objects;
DROP POLICY IF EXISTS "Allow Public Uploads Resumes" ON storage.objects;
DROP POLICY IF EXISTS "Allow Public View Resumes" ON storage.objects;
DROP POLICY IF EXISTS "Enable all for all" ON storage.objects;

-- Create robust policies for storage targeting both public and authenticated users (Clerk users)
CREATE POLICY "Allow Uploads Company Logo" ON storage.objects 
FOR INSERT TO anon, authenticated 
WITH CHECK (bucket_id = 'company-logo');

CREATE POLICY "Allow View Company Logo" ON storage.objects 
FOR SELECT TO anon, authenticated 
USING (bucket_id = 'company-logo');

CREATE POLICY "Allow Uploads Resumes" ON storage.objects 
FOR INSERT TO anon, authenticated 
WITH CHECK (bucket_id = 'resumes');

CREATE POLICY "Allow View Resumes" ON storage.objects 
FOR SELECT TO anon, authenticated 
USING (bucket_id = 'resumes');

-- NUCLEAR OPTION: Full access to ALL objects for ANYONE (Fixes 403 errors permanently)
-- IMPORTANT: Use this if the specific bucket policies above are not working.
DROP POLICY IF EXISTS "Full Access" ON storage.objects;
CREATE POLICY "Full Access" 
ON storage.objects FOR ALL 
TO anon, authenticated 
USING (true) 
WITH CHECK (true);
